### ISSUE TITLE
Implement new style handlers for observable properties in observers

### ISSUE THREAD

**Issue by rugui** [rugui/rugui#11]
Like we've done with signal handling, it would be nice if we could write something like:

<pre>
  when_property_change :my_property do |model, new_value, old_value|
    # do something
  end
</pre>

Or just:

<pre>
  property_changed :my_property do |model, new_value, old_value|
    # do something
  end
</pre>

**Comment by felipemesquita** [comment]
Hey dudes, this issue has already been implemented. Please, give a peek at http://github.com/rugui/rugui/commit/b40d6e6e6b4fbb20125c586d88d37f83a11ba4f6
