### ISSUE TITLE
Running in Ruby 1.9

### ISSUE THREAD

**Issue by davidbe** [rugui/rugui#19]
Different errors occur when using Ruby 1.9.

1st:
can't convert Pathname into String
/usr/lib/ruby/gems/1.9.1/gems/rugui-1.3.3/lib/rugui/framework_adapters/GTK.rb:67:in `sub'
--> put .to_s after configuration.root_path in line 67:  IO.read(File.join(path, filename)).sub('{ROOT_PATH}', RuGUI.configuration.root_path)

2nd:
/usr/lib/ruby/gems/1.9.1/gems/rugui-1.3.3/lib/rugui/framework_adapters/GTK.rb:15:in `ensure in instance_exec': undefined method`critical=' for Thread:Class
--> ?

More to come?

**Comment by vicentemundim** [comment]
Hi,
I've fixed these errors on master, could you take a look at it to see if it worked?

**Comment by davidbe** [comment]
First tests seem to work. :) Thanks for the quick fix!
