### ISSUE TITLE
New RuGUI app produces an error: no such file to load  -- app/../config/environment

### ISSUE THREAD

**Issue by thecatwasnot** [rugui/rugui#24]
Reproduce:
    $ rugui hellorugui
      create  
      create  README
      create  Rakefile
      create  bin
      create  bin/hellorugui
       chmod  bin/hellorugui
      create  bin/hellorugui.bat
       chmod  bin/hellorugui.bat
      create  app
      create  app/main.rb
      create  config
      create  config/environments/test.rb.sample
      create  config/environments/production.rb.sample
      create  config/environments/development.rb.sample
      create  config/boot.rb
      create  lib
      create  log
      create  vendor
      create  app/controllers
      create  app/controllers/application_controller.rb
      create  app/controllers/main_controller.rb
      create  app/views
      create  app/views/main_view.rb
      create  app/views/application_view.rb
      create  app/views/view_helpers/main_view_helper.rb
      create  app/views/view_helpers/application_view_helper.rb
      create  app/resources
      create  app/resources/styles/main.rc
      create  app/resources/glade/main_view.glade
      create  spec
      create  spec/spec.opts
      create  spec/rcov.opts
      create  spec/spec_helper.rb
    $ cd hellorugui/
    $ rake run
      (in /home/pixel/code/hellorugui)
      rake aborted!
      no such file to load -- /home/pixel/code/hellorugui/app/../config/environment

The main.rb file is trying to load an environment file that doesn't exist in a basic application.  Rails uses 2 kinds of environment files, the environment.rb file and then files like development.rb and test.rb for specific kinds of environments.  There are sample development.rb, test.rb and production.rb files provided by RuGUI but no environment.rb

**Comment by thecatwasnot** [comment]
Fixed in 1.4.3

**Comment by BeenaShetty** [comment]
Still there is an issue. I am using rugui (1.6.0).

It should be require File.join(File.expand_path('config') , 'environment')
