### ISSUE TITLE
rugui doesn't work with ruby 1.9

### ISSUE THREAD

**Issue by kronos** [rugui/rugui#25]
rugui test_ruqui && cd test_ruqui

<pre>
kronos:test_rugui kronos$ rake gems --trace
(in /Developer/ruby/test_rugui)
(eval):1: warning: redefining `object_id' may cause serious problem
(eval):1: warning: redefining `__send__' may cause serious problem
** Invoke gems (first_time)
** Invoke gems:base (first_time)
** Execute gems:base
** Invoke rake_environment (first_time)
** Execute rake_environment
rake aborted!
can't convert Pathname into String
/opt/local/lib/ruby/gems/1.9.1/gems/rugui-1.5.0/lib/rugui/initializer.rb:89:in `eval'
/opt/local/lib/ruby/gems/1.9.1/gems/rugui-1.5.0/lib/rugui/initializer.rb:89:in `load_environment'
/opt/local/lib/ruby/gems/1.9.1/gems/rugui-1.5.0/lib/rugui/initializer.rb:40:in `process'
/opt/local/lib/ruby/gems/1.9.1/gems/rugui-1.5.0/lib/rugui/initializer.rb:26:in `run'
/Developer/ruby/test_rugui/config/environment.rb:7:in `<top (required)>'
/opt/local/lib/ruby/gems/1.9.1/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
/opt/local/lib/ruby/gems/1.9.1/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `block in require'
/opt/local/lib/ruby/gems/1.9.1/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:521:in `new_constants_in'
/opt/local/lib/ruby/gems/1.9.1/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
/opt/local/lib/ruby/gems/1.9.1/gems/rugui-1.5.0/lib/rugui/tasks/gems_application.rake:3:in `block in <top (required)>'
/opt/local/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:636:in `call'
/opt/local/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:636:in `block in execute'
/opt/local/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:631:in `each'
/opt/local/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:631:in `execute'
/opt/local/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:597:in `block in invoke_with_call_chain'
/opt/local/lib/ruby/1.9.1/monitor.rb:190:in `mon_synchronize'
/opt/local/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/opt/local/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'
/opt/local/lib/ruby/gems/1.9.1/gems/rugui-1.5.0/lib/rugui/tasks/gems_application.rake:23:in `block (2 levels) in <top (required)>'
/opt/local/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:636:in `call'
/opt/local/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:636:in `block in execute'
/opt/local/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:631:in `each'
/opt/local/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:631:in `execute'
/opt/local/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:597:in `block in invoke_with_call_chain'
/opt/local/lib/ruby/1.9.1/monitor.rb:190:in `mon_synchronize'
/opt/local/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/opt/local/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:607:in `block in invoke_prerequisites'
/opt/local/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:604:in `each'
/opt/local/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:604:in `invoke_prerequisites'
/opt/local/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:596:in `block in invoke_with_call_chain'
/opt/local/lib/ruby/1.9.1/monitor.rb:190:in `mon_synchronize'
/opt/local/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/opt/local/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'
/opt/local/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2051:in `invoke_task'
/opt/local/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2029:in `block (2 levels) in top_level'
/opt/local/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2029:in `each'
/opt/local/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2029:in `block in top_level'
/opt/local/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/opt/local/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2023:in `top_level'
/opt/local/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2001:in `block in run'
/opt/local/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/opt/local/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
/opt/local/lib/ruby/gems/1.9.1/gems/rake-0.8.7/bin/rake:31:in `<top (required)>'
/opt/local/bin/rake:19:in `load'
/opt/local/bin/rake:19:in `<main>'
</pre>

**Comment by vicentemundim** [comment]
I am going to take a look at it. Could you post the config/environments/development.rb file?

**Comment by kronos** [comment]
of course: http://gist.github.com/363679
If I'm trying to use 1.8.7 I got this: http://gist.github.com/363682 (development.rb the same)

**Comment by l3x4** [comment]
Here's the patch which makes it run for me on ruby 1.9.2p0 with activesupport 3.0.1

<pre>
--------------------------- lib/rugui/initializer.rb ---------------------------
index e1632d7..b8db844 100644
@@ -73,7 +73,7 @@ module RuGUI
 
     # Set the paths from which RuGUI will automatically load source files.
     def set_autoload_paths
-      ActiveSupport::Dependencies.load_paths = configuration.load_paths.uniq
+      ActiveSupport::Dependencies.autoload_paths = configuration.load_paths.uniq
     end
 
     # Loads the environment specified by Configuration#environment_path, which
@@ -86,7 +86,7 @@ module RuGUI
         config = configuration
         constants = self.class.constants
 
-        eval(IO.read(configuration.environment_path), binding, configuration.environment_path)
+        eval(IO.read(configuration.environment_path))
 
         (self.class.constants - constants).each do |const|
           Object.const_set(const, self.class.const_get(const))
</pre>

**Comment by vicentemundim** [comment]
I've just pushed a patch that will address this. Just update your RuGUI to 1.6.0.
