### ISSUE TITLE
Button-Widget name empty?

### ISSUE THREAD

**Issue by marianeichholz** [rugui/rugui#34]
In the calculator example code, the widget in the event handler block appears to have an empty name property.
Oh, well, the issue appears with rugui-2.0.0.beta2.

``` ruby
  (0..9).each do |numerical_key|
    on "num_#{numerical_key}_button", 'clicked' do |widget|
      puts "widget is #{widget}"
      widname = widget.name
      puts "widget name is #{widname}"
      puts "Inspection: #{widget.inspect}"
      widmat = widname.match(/num_(\d)_button/)
      key = widmat[1]
      self.calculator.numerical_keys << key
    end
  end
```

When I press "7", this is found:

> widget is `#<Gtk::Button:0x000000019df1b0>`
> widget name is 
> Inspection: `#<Gtk::Button:0x19df1b0 ptr=0x21d04a0>`

eventually the match is empty and the key indexing fails. BOOM.

I do not understand this, as the "name" property should work as ever?! This is the object, as saved by Glade:

```
             <object class="GtkButton" id="num_7_button">
                <property name="label" translatable="yes">7</property>
                <property name="use_action_appearance">False</property>
                <property name="visible">True</property>
                <property name="can_focus">True</property>
                <property name="receives_default">True</property>
                <property name="use_action_appearance">False</property>
              </object>
```

Greetings, marian.

**Comment by vicentemundim** [comment]
I've just updated the simple_calculator to make it work. It seems that Gtk::Builder#name does not return the name defined in Glade, instead you have Gtk::Builder#builder_name.

**Comment by marianeichholz** [comment]
You are my hero! Well, with this minor change the calculator really works in my fork, too!

This change from "name" to "builder_name" looks **so** awkward. Where is it mentioned and ... "rationalized"? Probably this might help me and others to find a path through the API documentation...

Thanks again.

I still collect the necessary changes in a README.porting. Probably it evolves to something useful eventually :-)
- Marian

**Comment by vicentemundim** [comment]
This is probably a major version update. When a major version is bumped you can expect some backward incompatible changes in a framework. In this case it was from Glade 2.x to Glade 3.x, where they have changed the builder extension, as well as the builder API. You'll probably find this in the GTK documentation, but it is not one of the best documentations out there.
